os: osx

osx_image: xcode11.3

language: generic

before_install:
  - brew install mysql
  - brew services start mysql
  - brew install r
  - R -e 'install.packages(c( "rmarkdown"), repos = "http://cran.us.r-project.org")'
  - R --version

install:
  - brew cask install miniconda
  - conda update -q --all --yes conda
  - conda env create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file environment.yml
  - eval "$(/usr/local/bin/conda shell.bash hook)"
  - conda init
  - conda activate test-environment
  - snakemake renv_install
  - snakemake renv_init
  - snakemake renv_restore 
    
script:
  - cp -r tests/data/raw/* data/raw
  - snakemake --profile tests/settings -R sms_features
  - python -m unittest discover tests/scripts/ -v

cache:
  directories:
    - /usr/local/lib/R
    - $HOME/.local/share/renv
    - $TRAVIS_BUILD_DIR/renv/library

notifications:
  email: false
  slack:
    if: branch = travis_test
    secure: cJIpmIjb3zA5AMDBo9axF1v6fYNIgMm6s6UdMNOlHiT511xHGsaLUFej3lACwQLig4Gr94ySI61YdrP+RX1lFcYxusH+kUU/c8LX0PmSKNeKnycM3w/pCM+yTp/6oQG6ZrJD7pNm6zhB0xPL61uSmYhcr+JJ1sh4iLiON+J8/C+IfnAHm1ORkxJ0IxASkiP/LvaiAQDw8lNyYIZNWjSDNZbx68o1VNakyk6Vik3x8omiE3w33rzI2/JAx//QTxOq2J0dtV1AqYYSOWS4iXblV09NLBqgGrhAhrQ6+TbPHSPIyL/4EdhvS+YXO+SBWS7ODD7j/MuL6XiA4SujW72od2rgXNmOjFnlQvIrULO5bzv39BKKDkldvz9+XCyXLcjoLIwA/rmUnwMndNoC7NoD/CkQEevUxswXXB9811BmIFx/7GOHouVxwB2gaMAzkCroZJVwgbrc6ESSOVE5SMcb3wPMbpd8cXOgVZXJcmk5wK206zxXPigCvFfknqOnwDqRgyIWSFoTd/2wHppA7ND3R5U42nQTbEQ7MiONsOo61GlJTTxJELz32sLKl388AuAgOY7+0sqPibxMaHJkF1V4nYVTH0/H5bO/edK4VHMloJ6s0kuyko7LT5EMQf3pBJij5TnYmD2E60t+bSBAxHuH7WA5dvL+igjGEwROnxDc9pc=
    on_success: always
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"

  # branches:
  #   except:
  #     - master

  #   only:
  #     - travis_test
